# Generated by Django 3.2.15 on 2023-02-04 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='mediafile',
            name='customer_id',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='MediaFile',
        ),
    ]
