# Generated by Django 3.2.15 on 2022-10-21 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_customer_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer', verbose_name='Клиент'),
        ),
    ]
